conditioning:
  method: ps
  params:
    scale: 0.5

data:
  name: ffhq
  root: ./data/samples/

measurement:
  operator:
    name: inpainting_soc
  mask_opt:
    mask_type: box
    mask_len_range: !!python/tuple [128, 129]  # for box
    # mask_prob_range: !!python/tuple [0.3, 0.7]  # for random
    image_size: 256

  scale:
    linear:
      box: 0.6     # 0.55-0.65 之间
      random: 0.8
    nonlinear:
      box: 0.7
      random: 0.8
    nonlinear_finitegamma:
      box: 0.7
      random: 0.8

  mcmc:
    param:
      'tau': 0.01
      'lr_min_ratio': 0.01
      'prior_solver': 'gaussian'
      'mc_algo': 'langevin'
    nonlinear: 
      'num_steps': 100
      'lr': 0.00005
    nonlinear_finitegamma:
      1000:
        'num_steps': 300
        'lr': 0.00005
      100000:
        'num_steps': 300
        'lr': 0.00005
      10000000:
        'num_steps': 300
        'lr': 0.00005


  noise:
    name: gaussian
    sigma: 0.05
